PRAGMA foreign_keys=OFF;--> statement-breakpoint
CREATE TABLE `__new_task_style` (
	`id` text PRIMARY KEY DEFAULT 'singleton' NOT NULL,
	`display_show_done` integer DEFAULT true NOT NULL,
	`display_show_count` integer DEFAULT true NOT NULL,
	`display_use_checkboxes` integer DEFAULT true NOT NULL,
	`display_cross_on_done` integer DEFAULT true NOT NULL,
	`display_number_of_lines` integer DEFAULT 2 NOT NULL,
	`font_header` text DEFAULT 'Montserrat' NOT NULL,
	`font_body` text DEFAULT 'Roboto' NOT NULL,
	`scroll_enabled` integer DEFAULT true NOT NULL,
	`scroll_pixels_per_second` integer DEFAULT 70 NOT NULL,
	`scroll_gap_between_loops` integer DEFAULT 100 NOT NULL,
	`header_height` text DEFAULT '52px' NOT NULL,
	`header_bg_color` text DEFAULT '#091533' NOT NULL,
	`header_bg_opacity` real DEFAULT 0.95 NOT NULL,
	`header_border_color` text DEFAULT '#1b2b52' NOT NULL,
	`header_border_width` text DEFAULT '1px' NOT NULL,
	`header_border_radius` text DEFAULT '12px 12px 0 0' NOT NULL,
	`header_font_size` text DEFAULT '24px' NOT NULL,
	`header_font_color` text DEFAULT '#ffffff' NOT NULL,
	`header_padding` text DEFAULT '12px 16px' NOT NULL,
	`body_bg_color` text DEFAULT '#091533' NOT NULL,
	`body_bg_opacity` real DEFAULT 0.85 NOT NULL,
	`body_border_color` text DEFAULT '#1b2b52' NOT NULL,
	`body_border_width` text DEFAULT '1px' NOT NULL,
	`body_border_radius` text DEFAULT '0 0 12px 12px' NOT NULL,
	`body_padding_vertical` text DEFAULT '6px' NOT NULL,
	`body_padding_horizontal` text DEFAULT '6px' NOT NULL,
	`task_bg_color` text DEFAULT '#12244a' NOT NULL,
	`task_bg_opacity` real DEFAULT 0.9 NOT NULL,
	`task_border_color` text DEFAULT '#1b2b52' NOT NULL,
	`task_border_width` text DEFAULT '0px' NOT NULL,
	`task_border_radius` text DEFAULT '10px' NOT NULL,
	`task_font_size` text DEFAULT '22px' NOT NULL,
	`task_font_color` text DEFAULT '#eaf2ff' NOT NULL,
	`task_username_color` text DEFAULT '#6b8bf5' NOT NULL,
	`task_padding` text DEFAULT '10px 14px' NOT NULL,
	`task_margin_bottom` text DEFAULT '4px' NOT NULL,
	`task_max_width` text DEFAULT '100%' NOT NULL,
	`task_done_bg_color` text DEFAULT '#091533' NOT NULL,
	`task_done_bg_opacity` real DEFAULT 0.5 NOT NULL,
	`task_done_font_color` text DEFAULT '#7c8db0' NOT NULL,
	`checkbox_size` text DEFAULT '20px' NOT NULL,
	`checkbox_bg_color` text DEFAULT '#000000' NOT NULL,
	`checkbox_bg_opacity` real DEFAULT 0 NOT NULL,
	`checkbox_border_color` text DEFAULT '#4a5b82' NOT NULL,
	`checkbox_border_width` text DEFAULT '2px' NOT NULL,
	`checkbox_border_radius` text DEFAULT '6px' NOT NULL,
	`checkbox_margin_top` text DEFAULT '4px' NOT NULL,
	`checkbox_margin_left` text DEFAULT '2px' NOT NULL,
	`checkbox_margin_right` text DEFAULT '8px' NOT NULL,
	`checkbox_tick_char` text DEFAULT '✔' NOT NULL,
	`checkbox_tick_size` text DEFAULT '14px' NOT NULL,
	`checkbox_tick_color` text DEFAULT '#00aced' NOT NULL,
	`bullet_char` text DEFAULT '•' NOT NULL,
	`bullet_size` text DEFAULT '20px' NOT NULL,
	`bullet_color` text DEFAULT '#7c8db0' NOT NULL,
	`bullet_margin_top` text DEFAULT '0px' NOT NULL,
	`bullet_margin_left` text DEFAULT '2px' NOT NULL,
	`bullet_margin_right` text DEFAULT '8px' NOT NULL
);
--> statement-breakpoint
INSERT INTO `__new_task_style`("id", "display_show_done", "display_show_count", "display_use_checkboxes", "display_cross_on_done", "display_number_of_lines", "font_header", "font_body", "scroll_enabled", "scroll_pixels_per_second", "scroll_gap_between_loops", "header_height", "header_bg_color", "header_bg_opacity", "header_border_color", "header_border_width", "header_border_radius", "header_font_size", "header_font_color", "header_padding", "body_bg_color", "body_bg_opacity", "body_border_color", "body_border_width", "body_border_radius", "body_padding_vertical", "body_padding_horizontal", "task_bg_color", "task_bg_opacity", "task_border_color", "task_border_width", "task_border_radius", "task_font_size", "task_font_color", "task_username_color", "task_padding", "task_margin_bottom", "task_max_width", "task_done_bg_color", "task_done_bg_opacity", "task_done_font_color", "checkbox_size", "checkbox_bg_color", "checkbox_bg_opacity", "checkbox_border_color", "checkbox_border_width", "checkbox_border_radius", "checkbox_margin_top", "checkbox_margin_left", "checkbox_margin_right", "checkbox_tick_char", "checkbox_tick_size", "checkbox_tick_color", "bullet_char", "bullet_size", "bullet_color", "bullet_margin_top", "bullet_margin_left", "bullet_margin_right") SELECT "id", "display_show_done", "display_show_count", "display_use_checkboxes", "display_cross_on_done", "display_number_of_lines", "font_header", "font_body", "scroll_enabled", "scroll_pixels_per_second", "scroll_gap_between_loops", "header_height", "header_bg_color", "header_bg_opacity", "header_border_color", "header_border_width", "header_border_radius", "header_font_size", "header_font_color", "header_padding", "body_bg_color", "body_bg_opacity", "body_border_color", "body_border_width", "body_border_radius", "body_padding_vertical", "body_padding_horizontal", "task_bg_color", "task_bg_opacity", "task_border_color", "task_border_width", "task_border_radius", "task_font_size", "task_font_color", "task_username_color", "task_padding", "task_margin_bottom", "task_max_width", "task_done_bg_color", "task_done_bg_opacity", "task_done_font_color", "checkbox_size", "checkbox_bg_color", "checkbox_bg_opacity", "checkbox_border_color", "checkbox_border_width", "checkbox_border_radius", "checkbox_margin_top", "checkbox_margin_left", "checkbox_margin_right", "checkbox_tick_char", "checkbox_tick_size", "checkbox_tick_color", "bullet_char", "bullet_size", "bullet_color", "bullet_margin_top", "bullet_margin_left", "bullet_margin_right" FROM `task_style`;--> statement-breakpoint
DROP TABLE `task_style`;--> statement-breakpoint
ALTER TABLE `__new_task_style` RENAME TO `task_style`;--> statement-breakpoint
PRAGMA foreign_keys=ON;--> statement-breakpoint
CREATE TABLE `__new_timer_style` (
	`id` text PRIMARY KEY DEFAULT 'singleton' NOT NULL,
	`width` text DEFAULT '250px' NOT NULL,
	`height` text DEFAULT '250px' NOT NULL,
	`bg_color` text DEFAULT '#091533' NOT NULL,
	`bg_opacity` real DEFAULT 0.85 NOT NULL,
	`bg_border_radius` text DEFAULT '22%' NOT NULL,
	`ring_enabled` integer DEFAULT true NOT NULL,
	`ring_track_color` text DEFAULT '#ffffff' NOT NULL,
	`ring_track_opacity` real DEFAULT 0.18 NOT NULL,
	`ring_fill_color` text DEFAULT '#00aced' NOT NULL,
	`ring_fill_opacity` real DEFAULT 1 NOT NULL,
	`ring_width` integer DEFAULT 8 NOT NULL,
	`ring_gap` integer DEFAULT 6 NOT NULL,
	`text_color` text DEFAULT '#ffffff' NOT NULL,
	`text_outline_color` text DEFAULT '#000000' NOT NULL,
	`text_outline_size` text DEFAULT '0px' NOT NULL,
	`text_font_family` text DEFAULT 'Montserrat' NOT NULL,
	`font_size_label` text DEFAULT '18px' NOT NULL,
	`font_size_time` text DEFAULT '48px' NOT NULL,
	`font_size_cycle` text DEFAULT '16px' NOT NULL
);
--> statement-breakpoint
INSERT INTO `__new_timer_style`("id", "width", "height", "bg_color", "bg_opacity", "bg_border_radius", "ring_enabled", "ring_track_color", "ring_track_opacity", "ring_fill_color", "ring_fill_opacity", "ring_width", "ring_gap", "text_color", "text_outline_color", "text_outline_size", "text_font_family", "font_size_label", "font_size_time", "font_size_cycle") SELECT "id", "width", "height", "bg_color", "bg_opacity", "bg_border_radius", "ring_enabled", "ring_track_color", "ring_track_opacity", "ring_fill_color", "ring_fill_opacity", "ring_width", "ring_gap", "text_color", "text_outline_color", "text_outline_size", "text_font_family", "font_size_label", "font_size_time", "font_size_cycle" FROM `timer_style`;--> statement-breakpoint
DROP TABLE `timer_style`;--> statement-breakpoint
ALTER TABLE `__new_timer_style` RENAME TO `timer_style`;--> statement-breakpoint
UPDATE `timer_style` SET `ring_track_opacity` = 0.18 WHERE `ring_track_opacity` = 0.1;