[phases.setup]
nixPkgs = ["nodejs_20", "bun"]

[phases.install]
cmds = ["bun install --frozen-lockfile"]

[phases.build]
cmds = ["SKIP_ENV_VALIDATION=true bun run build"]

[start]
cmd = "node apps/web/.next/standalone/apps/web/server.js"
