/**
 * Self-host the overlay font families: downloads latin woff2 subsets from
 * Google Fonts and generates public/fonts/fonts.css with same-origin URLs.
 *
 * Run from apps/web: `bun run fetch-fonts`
 * Commit the output — builds and deploys stay offline/deterministic, and the
 * worker serves the files as static assets (Cloudflare edge cache, no
 * third-party request from viewers' OBS browser sources).
 *
 * @font-face is lazy: shipping every family in one stylesheet costs one small
 * CSS file; browsers only fetch the woff2 for families actually rendered.
 */
import { mkdir, rm, writeFile } from "node:fs/promises";
import path from "node:path";

import { FONT_OPTIONS } from "../src/lib/overlay-font-options";

const OUT_DIR = path.join(import.meta.dirname, "../public/fonts");
// Chrome UA so Google serves woff2 with unicode-range subsets.
const UA =
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0 Safari/537.36";
const WEIGHTS = [400, 500, 600, 700];

interface Face {
  family: string;
  weight: string;
  style: string;
  url: string;
}

async function fetchCss(family: string): Promise<string | null> {
  const plus = family.replace(/ /g, "+");
  const candidates = [
    // Variable range first (one file per family when supported)…
    `https://fonts.googleapis.com/css2?family=${plus}:wght@${WEIGHTS[0]}..${WEIGHTS.at(-1)}&display=swap`,
    // …then static instances…
    `https://fonts.googleapis.com/css2?family=${plus}:wght@${WEIGHTS.join(";")}&display=swap`,
    // …then whatever the family has (single-weight families like Fredoka One)…
    `https://fonts.googleapis.com/css2?family=${plus}&display=swap`,
    // …and the legacy API for names css2 doesn't know.
    `https://fonts.googleapis.com/css?family=${plus}:${WEIGHTS.join(",")}&display=swap`,
    `https://fonts.googleapis.com/css?family=${plus}&display=swap`,
  ];
  for (const url of candidates) {
    const res = await fetch(url, { headers: { "User-Agent": UA } });
    if (res.ok) return res.text();
  }
  return null;
}

/** Keep only latin-subset blocks (css2 labels them; legacy CSS has no labels — keep all). */
function latinBlocks(css: string): string[] {
  const labeled = [...css.matchAll(/\/\* ([a-z0-9-]+) \*\/\s*(@font-face\s*\{[^}]+\})/g)];
  if (labeled.length === 0) return [...css.matchAll(/@font-face\s*\{[^}]+\}/g)].map((m) => m[0]);
  return labeled.filter((m) => m[1] === "latin").map((m) => m[2]);
}

function parseFace(block: string, family: string): Face | null {
  const url = block.match(/url\((https:[^)]+\.woff2)\)/)?.[1];
  if (!url) return null;
  return {
    family,
    weight: block.match(/font-weight:\s*([^;]+);/)?.[1]?.trim() ?? "400",
    style: block.match(/font-style:\s*([^;]+);/)?.[1]?.trim() ?? "normal",
    url,
  };
}

await rm(OUT_DIR, { recursive: true, force: true });
await mkdir(OUT_DIR, { recursive: true });

const cssParts: string[] = [
  "/* GENERATED by apps/web/scripts/fetch-fonts.ts — do not edit by hand.",
  " * Latin subsets of Google Fonts families (OFL/Apache licensed) self-hosted",
  " * as worker static assets. See LICENSE.txt in this directory. */",
  "",
];
let fileCount = 0;
let byteCount = 0;

for (const family of FONT_OPTIONS) {
  const css = await fetchCss(family);
  if (!css) {
    console.error(`FAIL ${family}: no CSS from any endpoint`);
    process.exitCode = 1;
    continue;
  }
  const faces = latinBlocks(css)
    .map((b) => parseFace(b, family))
    .filter((f): f is Face => f !== null);
  // Dedupe identical weight+style (variable-range responses repeat)
  const seen = new Set<string>();
  const slug = family.toLowerCase().replace(/ /g, "-");
  for (const face of faces) {
    const key = `${face.weight}|${face.style}`;
    if (seen.has(key) || face.style !== "normal") continue;
    seen.add(key);
    const res = await fetch(face.url, { headers: { "User-Agent": UA } });
    if (!res.ok) {
      console.error(`FAIL ${family} ${face.weight}: ${res.status}`);
      process.exitCode = 1;
      continue;
    }
    const buf = Buffer.from(await res.arrayBuffer());
    const file = `${slug}-${face.weight.replace(/ /g, "_")}.woff2`;
    await writeFile(path.join(OUT_DIR, file), buf);
    fileCount += 1;
    byteCount += buf.length;
    cssParts.push(
      `@font-face {`,
      `  font-family: "${family}";`,
      `  font-style: normal;`,
      `  font-weight: ${face.weight};`,
      `  font-display: swap;`,
      `  src: url("./${file}") format("woff2");`,
      `}`,
      "",
    );
  }
  console.log(`ok ${family}: ${seen.size} face(s)`);
}

await writeFile(path.join(OUT_DIR, "fonts.css"), cssParts.join("\n"));
await writeFile(
  path.join(OUT_DIR, "LICENSE.txt"),
  `The font files in this directory are latin subsets of Google Fonts families,\n` +
    `self-hosted for Dirework's OBS overlays and Theme Center. Each family is\n` +
    `licensed under the SIL Open Font License 1.1 or Apache License 2.0 by its\n` +
    `respective author — see https://fonts.google.com/ for per-family details.\n\n` +
    `Families: ${FONT_OPTIONS.join(", ")}\n`,
);
console.log(`\n${fileCount} files, ${(byteCount / 1024).toFixed(0)} KiB total`);
