/**
 * Self-host the overlay font families: downloads latin woff2 subsets from
 * Google Fonts and generates public/fonts/fonts.css with same-origin URLs.
 *
 * Run from apps/web: `bun run fetch-fonts`
 * Commit the output — builds and deploys stay offline/deterministic, and the
 * worker serves the files as static assets (Cloudflare edge cache, no
 * third-party request from viewers' OBS browser sources).
 *
 * @font-face is lazy: shipping every family in one stylesheet costs one small
 * CSS file; browsers only fetch the woff2 for families actually rendered.
 */
import { copyFile, mkdir, mkdtemp, readdir, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";

import { FONT_OPTIONS } from "../src/lib/overlay-font-options";
import { type Face, faceFileName, isWoff2, latinBlocks, parseFace } from "./font-faces";

const OUT_DIR = path.join(import.meta.dirname, "../public/fonts");
// Chrome UA so Google serves woff2 with unicode-range subsets.
const UA =
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0 Safari/537.36";
const WEIGHTS = [400, 500, 600, 700];

async function fetchCss(family: string): Promise<string | null> {
  const plus = family.replace(/ /g, "+");
  const candidates = [
    // Variable range first (one file per family when supported)…
    `https://fonts.googleapis.com/css2?family=${plus}:wght@${WEIGHTS[0]}..${WEIGHTS.at(-1)}&display=swap`,
    // …then static instances…
    `https://fonts.googleapis.com/css2?family=${plus}:wght@${WEIGHTS.join(";")}&display=swap`,
    // …then whatever the family has (single-weight families like Fredoka One)…
    `https://fonts.googleapis.com/css2?family=${plus}&display=swap`,
    // …and the legacy API for names css2 doesn't know.
    `https://fonts.googleapis.com/css?family=${plus}:${WEIGHTS.join(",")}&display=swap`,
    `https://fonts.googleapis.com/css?family=${plus}&display=swap`,
  ];
  for (const url of candidates) {
    const res = await fetch(url, { headers: { "User-Agent": UA } });
    if (res.ok) return res.text();
  }
  return null;
}

// Download into a staging dir; public/fonts is only touched once EVERY family
// succeeded, so a rate-limited or partial run never leaves a gutted font set.
const STAGE_DIR = await mkdtemp(path.join(tmpdir(), "dirework-fonts-"));
let failed = false;
const fail = (message: string) => {
  console.error(`FAIL ${message}`);
  failed = true;
};

const cssParts: string[] = [
  "/* GENERATED by apps/web/scripts/fetch-fonts.ts — do not edit by hand.",
  " * Latin subsets of Google Fonts families (OFL/Apache licensed) self-hosted",
  " * as worker static assets. See LICENSE.txt in this directory. */",
  "",
];
let fileCount = 0;
let byteCount = 0;

for (const family of FONT_OPTIONS) {
  const css = await fetchCss(family);
  if (!css) {
    fail(`${family}: no CSS from any endpoint`);
    continue;
  }
  const blocks = latinBlocks(css);
  const faces = blocks.map((b) => parseFace(b, family)).filter((f): f is Face => f !== null);
  if (faces.length < blocks.length) {
    fail(`${family}: ${blocks.length - faces.length} @font-face block(s) failed validation`);
  }
  // Dedupe identical weight+style (variable-range responses repeat)
  const seen = new Set<string>();
  for (const face of faces) {
    const key = `${face.weight}|${face.style}`;
    if (seen.has(key) || face.style !== "normal") continue;
    seen.add(key);
    const res = await fetch(face.url, { headers: { "User-Agent": UA } });
    if (!res.ok) {
      fail(`${family} ${face.weight}: ${res.status}`);
      continue;
    }
    const buf = Buffer.from(await res.arrayBuffer());
    if (!isWoff2(buf)) {
      fail(`${family} ${face.weight}: response is not a woff2 file`);
      continue;
    }
    const file = faceFileName(OUT_DIR, family, face.weight);
    await writeFile(path.join(STAGE_DIR, file), buf);
    fileCount += 1;
    byteCount += buf.length;
    cssParts.push(
      `@font-face {`,
      `  font-family: "${family}";`,
      `  font-style: normal;`,
      `  font-weight: ${face.weight};`,
      `  font-display: swap;`,
      `  src: url("./${file}") format("woff2");`,
      `}`,
      "",
    );
  }
  if (seen.size === 0) fail(`${family}: no usable faces`);
  else console.log(`ok ${family}: ${seen.size} face(s)`);
}

if (failed) {
  await rm(STAGE_DIR, { recursive: true, force: true });
  console.error("\nAborted: public/fonts left unchanged. Re-run once every family downloads.");
  process.exit(1);
}

await writeFile(path.join(STAGE_DIR, "fonts.css"), cssParts.join("\n"));

// Swap in only generated artifacts — LICENSE.txt and the full license texts
// (OFL-1.1.txt, Apache-2.0.txt, UFL-1.0.txt) are hand-curated and must survive.
await mkdir(OUT_DIR, { recursive: true });
for (const entry of await readdir(OUT_DIR)) {
  if (entry.endsWith(".woff2") || entry === "fonts.css") {
    await rm(path.join(OUT_DIR, entry));
  }
}
for (const entry of await readdir(STAGE_DIR)) {
  await copyFile(path.join(STAGE_DIR, entry), path.join(OUT_DIR, entry));
}
await rm(STAGE_DIR, { recursive: true, force: true });

console.log(`\n${fileCount} files, ${(byteCount / 1024).toFixed(0)} KiB total`);
console.log("Reminder: adding a family? Update the hand-curated LICENSE.txt mapping.");
