import type { ThemePreset, TimerStylesConfig, TaskStylesConfig } from "./config-types";

export const defaultTimerStyles: TimerStylesConfig = {
  dimensions: { width: "250px", height: "250px" },
  background: { color: "#000000", opacity: 0.5, borderRadius: "50%" },
  text: { color: "#ffffff", outlineColor: "#000000", outlineSize: "0px", fontFamily: "Inter" },
  fontSizes: { label: "24px", time: "48px", cycle: "20px" },
};

export const defaultTaskStyles: TaskStylesConfig = {
  display: {
    showDone: true,
    showCount: true,
    useCheckboxes: true,
    crossOnDone: true,
    numberOfLines: 2,
  },
  fonts: { header: "Fredoka One", body: "Nunito" },
  scroll: { pixelsPerSecond: 70, gapBetweenLoops: 100 },
  header: {
    height: "60px",
    background: { color: "#000000", opacity: 0.9 },
    border: { color: "#ffffff", width: "2px", radius: "10px" },
    fontSize: "30px",
    fontColor: "#ffffff",
    padding: "10px",
  },
  body: {
    background: { color: "#000000", opacity: 0 },
    border: { color: "#ffffff", width: "0px", radius: "0px" },
    padding: { vertical: "5px", horizontal: "5px" },
  },
  task: {
    background: { color: "#000000", opacity: 0.8 },
    border: { color: "#000000", width: "0px", radius: "5px" },
    fontSize: "25px",
    fontColor: "#ffffff",
    usernameColor: "#ffffff",
    padding: "10px",
    marginBottom: "5px",
    maxWidth: "100%",
    direction: "row",
  },
  taskDone: {
    background: { color: "#000000", opacity: 0.5 },
    fontColor: "#bbbbbb",
  },
  checkbox: {
    size: "20px",
    background: { color: "#000000", opacity: 0 },
    border: { color: "#ffffff", width: "1px", radius: "3px" },
    margin: { top: "6px", left: "2px", right: "5px" },
    tickChar: "\u2714",
    tickSize: "18px",
    tickColor: "#ffffff",
  },
  bullet: {
    char: "\u2022",
    size: "20px",
    color: "#ffffff",
    margin: { top: "0px", left: "2px", right: "5px" },
  },
};

export const themePresets: ThemePreset[] = [
  // 1. Default
  {
    id: "default",
    name: "Default",
    description: "Classic dark theme with white text",
    preview: { bg: "#000000", accent: "#ffffff", text: "#ffffff" },
    timerStyles: { ...defaultTimerStyles },
    taskStyles: { ...defaultTaskStyles },
  },

  // 2. macOS Liquid Glass
  {
    id: "glass",
    name: "Liquid Glass",
    description: "Frosted translucent panels with glass-like opacity",
    preview: { bg: "#f0f0f0", accent: "#ffffff", text: "#1a1a2e" },
    timerStyles: {
      dimensions: { width: "250px", height: "250px" },
      background: { color: "#ffffff", opacity: 0.25, borderRadius: "50%" },
      text: { color: "#1a1a2e", outlineColor: "#ffffff", outlineSize: "1px", fontFamily: "Inter" },
      fontSizes: { label: "24px", time: "48px", cycle: "20px" },
    },
    taskStyles: {
      display: { showDone: true, showCount: true, useCheckboxes: true, crossOnDone: true, numberOfLines: 2 },
      fonts: { header: "Inter", body: "Inter" },
      scroll: { pixelsPerSecond: 70, gapBetweenLoops: 100 },
      header: {
        height: "60px",
        background: { color: "#ffffff", opacity: 0.3 },
        border: { color: "#ffffff", width: "1px", radius: "16px" },
        fontSize: "30px",
        fontColor: "#1a1a2e",
        padding: "10px",
      },
      body: {
        background: { color: "#ffffff", opacity: 0.15 },
        border: { color: "#ffffff", width: "1px", radius: "0 0 16px 16px" },
        padding: { vertical: "5px", horizontal: "5px" },
      },
      task: {
        background: { color: "#ffffff", opacity: 0.2 },
        border: { color: "#ffffff", width: "1px", radius: "12px" },
        fontSize: "25px",
        fontColor: "#1a1a2e",
        usernameColor: "#6366f1",
        padding: "10px",
        marginBottom: "5px",
        maxWidth: "100%",
        direction: "row",
      },
      taskDone: { background: { color: "#ffffff", opacity: 0.1 }, fontColor: "#888888" },
      checkbox: {
        size: "20px",
        background: { color: "#ffffff", opacity: 0.2 },
        border: { color: "#c0c0c0", width: "1px", radius: "6px" },
        margin: { top: "6px", left: "2px", right: "5px" },
        tickChar: "\u2714",
        tickSize: "18px",
        tickColor: "#6366f1",
      },
      bullet: { char: "\u2022", size: "20px", color: "#1a1a2e", margin: { top: "0px", left: "2px", right: "5px" } },
    },
  },

  // 3. Neon Cyberpunk
  {
    id: "neon-cyberpunk",
    name: "Neon Cyberpunk",
    description: "Dark backgrounds with neon green and pink accents",
    preview: { bg: "#0a0a0f", accent: "#00ff9f", text: "#00ff9f" },
    timerStyles: {
      dimensions: { width: "250px", height: "250px" },
      background: { color: "#0a0a0f", opacity: 0.9, borderRadius: "0%" },
      text: { color: "#00ff9f", outlineColor: "#ff006e", outlineSize: "2px", fontFamily: "Share Tech Mono" },
      fontSizes: { label: "24px", time: "48px", cycle: "20px" },
    },
    taskStyles: {
      display: { showDone: true, showCount: true, useCheckboxes: true, crossOnDone: true, numberOfLines: 2 },
      fonts: { header: "Share Tech Mono", body: "Share Tech Mono" },
      scroll: { pixelsPerSecond: 70, gapBetweenLoops: 100 },
      header: {
        height: "60px",
        background: { color: "#0a0a0f", opacity: 0.95 },
        border: { color: "#00ff9f", width: "2px", radius: "0px" },
        fontSize: "30px",
        fontColor: "#00ff9f",
        padding: "10px",
      },
      body: {
        background: { color: "#0a0a0f", opacity: 0.85 },
        border: { color: "#ff006e", width: "1px", radius: "0px" },
        padding: { vertical: "5px", horizontal: "5px" },
      },
      task: {
        background: { color: "#1a0a2e", opacity: 0.9 },
        border: { color: "#00ff9f", width: "1px", radius: "0px" },
        fontSize: "25px",
        fontColor: "#e0e0e0",
        usernameColor: "#ff006e",
        padding: "10px",
        marginBottom: "5px",
        maxWidth: "100%",
        direction: "row",
      },
      taskDone: { background: { color: "#0a0a0f", opacity: 0.6 }, fontColor: "#555555" },
      checkbox: {
        size: "20px",
        background: { color: "#0a0a0f", opacity: 0 },
        border: { color: "#00ff9f", width: "2px", radius: "0px" },
        margin: { top: "6px", left: "2px", right: "5px" },
        tickChar: "\u2714",
        tickSize: "18px",
        tickColor: "#00ff9f",
      },
      bullet: { char: ">", size: "20px", color: "#00ff9f", margin: { top: "0px", left: "2px", right: "5px" } },
    },
  },

  // 4. Cozy Cottage
  {
    id: "cozy-cottage",
    name: "Cozy Cottage",
    description: "Warm earth tones with a soft cream and brown palette",
    preview: { bg: "#f5e6d3", accent: "#8b6914", text: "#4a3520" },
    timerStyles: {
      dimensions: { width: "250px", height: "250px" },
      background: { color: "#f5e6d3", opacity: 0.9, borderRadius: "50%" },
      text: { color: "#4a3520", outlineColor: "#f5e6d3", outlineSize: "0px", fontFamily: "Nunito" },
      fontSizes: { label: "24px", time: "48px", cycle: "20px" },
    },
    taskStyles: {
      display: { showDone: true, showCount: true, useCheckboxes: true, crossOnDone: true, numberOfLines: 2 },
      fonts: { header: "Fredoka One", body: "Nunito" },
      scroll: { pixelsPerSecond: 70, gapBetweenLoops: 100 },
      header: {
        height: "60px",
        background: { color: "#8b6914", opacity: 0.9 },
        border: { color: "#c4a35a", width: "2px", radius: "16px" },
        fontSize: "30px",
        fontColor: "#fff8ee",
        padding: "10px",
      },
      body: {
        background: { color: "#f5e6d3", opacity: 0.85 },
        border: { color: "#c4a35a", width: "1px", radius: "0 0 16px 16px" },
        padding: { vertical: "5px", horizontal: "5px" },
      },
      task: {
        background: { color: "#fff8ee", opacity: 0.9 },
        border: { color: "#e0d0b8", width: "1px", radius: "12px" },
        fontSize: "25px",
        fontColor: "#4a3520",
        usernameColor: "#8b6914",
        padding: "10px",
        marginBottom: "5px",
        maxWidth: "100%",
        direction: "row",
      },
      taskDone: { background: { color: "#e8dcc8", opacity: 0.7 }, fontColor: "#a09080" },
      checkbox: {
        size: "20px",
        background: { color: "#fff8ee", opacity: 0.5 },
        border: { color: "#c4a35a", width: "1px", radius: "4px" },
        margin: { top: "6px", left: "2px", right: "5px" },
        tickChar: "\u2714",
        tickSize: "18px",
        tickColor: "#8b6914",
      },
      bullet: { char: "\u2022", size: "20px", color: "#8b6914", margin: { top: "0px", left: "2px", right: "5px" } },
    },
  },

  // 5. Ocean Depths
  {
    id: "ocean-depths",
    name: "Ocean Depths",
    description: "Deep navy and teal with slight transparency",
    preview: { bg: "#0a1628", accent: "#2dd4bf", text: "#e0f2fe" },
    timerStyles: {
      dimensions: { width: "250px", height: "250px" },
      background: { color: "#0a1628", opacity: 0.85, borderRadius: "50%" },
      text: { color: "#e0f2fe", outlineColor: "#0a1628", outlineSize: "1px", fontFamily: "Inter" },
      fontSizes: { label: "24px", time: "48px", cycle: "20px" },
    },
    taskStyles: {
      display: { showDone: true, showCount: true, useCheckboxes: true, crossOnDone: true, numberOfLines: 2 },
      fonts: { header: "Inter", body: "Inter" },
      scroll: { pixelsPerSecond: 70, gapBetweenLoops: 100 },
      header: {
        height: "60px",
        background: { color: "#0a1628", opacity: 0.95 },
        border: { color: "#2dd4bf", width: "2px", radius: "10px" },
        fontSize: "30px",
        fontColor: "#e0f2fe",
        padding: "10px",
      },
      body: {
        background: { color: "#0e1f3d", opacity: 0.8 },
        border: { color: "#1e3a5f", width: "1px", radius: "0 0 10px 10px" },
        padding: { vertical: "5px", horizontal: "5px" },
      },
      task: {
        background: { color: "#0e1f3d", opacity: 0.9 },
        border: { color: "#1e3a5f", width: "1px", radius: "8px" },
        fontSize: "25px",
        fontColor: "#e0f2fe",
        usernameColor: "#2dd4bf",
        padding: "10px",
        marginBottom: "5px",
        maxWidth: "100%",
        direction: "row",
      },
      taskDone: { background: { color: "#0a1628", opacity: 0.6 }, fontColor: "#6b8db5" },
      checkbox: {
        size: "20px",
        background: { color: "#0a1628", opacity: 0 },
        border: { color: "#2dd4bf", width: "1px", radius: "3px" },
        margin: { top: "6px", left: "2px", right: "5px" },
        tickChar: "\u2714",
        tickSize: "18px",
        tickColor: "#2dd4bf",
      },
      bullet: { char: "\u2022", size: "20px", color: "#2dd4bf", margin: { top: "0px", left: "2px", right: "5px" } },
    },
  },

  // 6. Sakura
  {
    id: "sakura",
    name: "Sakura",
    description: "Soft pinks and pastels with gentle rounded corners",
    preview: { bg: "#fff0f5", accent: "#ff69b4", text: "#d63384" },
    timerStyles: {
      dimensions: { width: "250px", height: "250px" },
      background: { color: "#fff0f5", opacity: 0.9, borderRadius: "50%" },
      text: { color: "#d63384", outlineColor: "#ffffff", outlineSize: "0px", fontFamily: "Nunito" },
      fontSizes: { label: "24px", time: "48px", cycle: "20px" },
    },
    taskStyles: {
      display: { showDone: true, showCount: true, useCheckboxes: true, crossOnDone: true, numberOfLines: 2 },
      fonts: { header: "Fredoka One", body: "Nunito" },
      scroll: { pixelsPerSecond: 70, gapBetweenLoops: 100 },
      header: {
        height: "60px",
        background: { color: "#ff69b4", opacity: 0.85 },
        border: { color: "#ffb6c1", width: "2px", radius: "16px" },
        fontSize: "30px",
        fontColor: "#ffffff",
        padding: "10px",
      },
      body: {
        background: { color: "#fff0f5", opacity: 0.8 },
        border: { color: "#ffb6c1", width: "1px", radius: "0 0 16px 16px" },
        padding: { vertical: "5px", horizontal: "5px" },
      },
      task: {
        background: { color: "#ffffff", opacity: 0.85 },
        border: { color: "#ffb6c1", width: "1px", radius: "12px" },
        fontSize: "25px",
        fontColor: "#4a2040",
        usernameColor: "#d63384",
        padding: "10px",
        marginBottom: "5px",
        maxWidth: "100%",
        direction: "row",
      },
      taskDone: { background: { color: "#fff0f5", opacity: 0.5 }, fontColor: "#c8a0b0" },
      checkbox: {
        size: "20px",
        background: { color: "#fff0f5", opacity: 0.5 },
        border: { color: "#ff69b4", width: "1px", radius: "50%" },
        margin: { top: "6px", left: "2px", right: "5px" },
        tickChar: "\u2764",
        tickSize: "14px",
        tickColor: "#ff69b4",
      },
      bullet: { char: "\u2727", size: "20px", color: "#ff69b4", margin: { top: "0px", left: "2px", right: "5px" } },
    },
  },

  // 7. Retro Terminal
  {
    id: "retro-terminal",
    name: "Retro Terminal",
    description: "Green-on-black monospace with sharp corners",
    preview: { bg: "#0a0a0a", accent: "#00ff00", text: "#00ff00" },
    timerStyles: {
      dimensions: { width: "250px", height: "250px" },
      background: { color: "#0a0a0a", opacity: 0.95, borderRadius: "0%" },
      text: { color: "#00ff00", outlineColor: "#003300", outlineSize: "1px", fontFamily: "Share Tech Mono" },
      fontSizes: { label: "24px", time: "48px", cycle: "20px" },
    },
    taskStyles: {
      display: { showDone: true, showCount: true, useCheckboxes: false, crossOnDone: true, numberOfLines: 2 },
      fonts: { header: "Share Tech Mono", body: "Share Tech Mono" },
      scroll: { pixelsPerSecond: 70, gapBetweenLoops: 100 },
      header: {
        height: "60px",
        background: { color: "#0a0a0a", opacity: 0.95 },
        border: { color: "#00ff00", width: "1px", radius: "0px" },
        fontSize: "30px",
        fontColor: "#00ff00",
        padding: "10px",
      },
      body: {
        background: { color: "#0a0a0a", opacity: 0.9 },
        border: { color: "#00ff00", width: "1px", radius: "0px" },
        padding: { vertical: "5px", horizontal: "5px" },
      },
      task: {
        background: { color: "#0a0a0a", opacity: 0.8 },
        border: { color: "#003300", width: "1px", radius: "0px" },
        fontSize: "25px",
        fontColor: "#00ff00",
        usernameColor: "#00cc00",
        padding: "10px",
        marginBottom: "5px",
        maxWidth: "100%",
        direction: "row",
      },
      taskDone: { background: { color: "#0a0a0a", opacity: 0.5 }, fontColor: "#006600" },
      checkbox: {
        size: "20px",
        background: { color: "#0a0a0a", opacity: 0 },
        border: { color: "#00ff00", width: "1px", radius: "0px" },
        margin: { top: "6px", left: "2px", right: "5px" },
        tickChar: "X",
        tickSize: "18px",
        tickColor: "#00ff00",
      },
      bullet: { char: ">", size: "20px", color: "#00ff00", margin: { top: "0px", left: "2px", right: "5px" } },
    },
  },

  // 8. Minimal Light
  {
    id: "minimal-light",
    name: "Minimal Light",
    description: "White and light gray with thin borders for readability",
    preview: { bg: "#ffffff", accent: "#e5e7eb", text: "#111827" },
    timerStyles: {
      dimensions: { width: "250px", height: "250px" },
      background: { color: "#ffffff", opacity: 0.95, borderRadius: "50%" },
      text: { color: "#111827", outlineColor: "#ffffff", outlineSize: "0px", fontFamily: "Inter" },
      fontSizes: { label: "24px", time: "48px", cycle: "20px" },
    },
    taskStyles: {
      display: { showDone: true, showCount: true, useCheckboxes: true, crossOnDone: true, numberOfLines: 2 },
      fonts: { header: "Inter", body: "Inter" },
      scroll: { pixelsPerSecond: 70, gapBetweenLoops: 100 },
      header: {
        height: "60px",
        background: { color: "#f9fafb", opacity: 0.98 },
        border: { color: "#e5e7eb", width: "1px", radius: "8px" },
        fontSize: "30px",
        fontColor: "#111827",
        padding: "10px",
      },
      body: {
        background: { color: "#ffffff", opacity: 0.95 },
        border: { color: "#e5e7eb", width: "1px", radius: "0 0 8px 8px" },
        padding: { vertical: "5px", horizontal: "5px" },
      },
      task: {
        background: { color: "#f9fafb", opacity: 0.95 },
        border: { color: "#e5e7eb", width: "1px", radius: "6px" },
        fontSize: "25px",
        fontColor: "#111827",
        usernameColor: "#6366f1",
        padding: "10px",
        marginBottom: "5px",
        maxWidth: "100%",
        direction: "row",
      },
      taskDone: { background: { color: "#f3f4f6", opacity: 0.8 }, fontColor: "#9ca3af" },
      checkbox: {
        size: "20px",
        background: { color: "#ffffff", opacity: 1 },
        border: { color: "#d1d5db", width: "1px", radius: "4px" },
        margin: { top: "6px", left: "2px", right: "5px" },
        tickChar: "\u2714",
        tickSize: "18px",
        tickColor: "#6366f1",
      },
      bullet: { char: "\u2022", size: "20px", color: "#6b7280", margin: { top: "0px", left: "2px", right: "5px" } },
    },
  },

  // 9. Sunset
  {
    id: "sunset",
    name: "Sunset",
    description: "Warm oranges and purples with medium opacity",
    preview: { bg: "#1a0a2e", accent: "#ff6b35", text: "#ffd700" },
    timerStyles: {
      dimensions: { width: "250px", height: "250px" },
      background: { color: "#1a0a2e", opacity: 0.85, borderRadius: "50%" },
      text: { color: "#ffd700", outlineColor: "#1a0a2e", outlineSize: "1px", fontFamily: "Inter" },
      fontSizes: { label: "24px", time: "48px", cycle: "20px" },
    },
    taskStyles: {
      display: { showDone: true, showCount: true, useCheckboxes: true, crossOnDone: true, numberOfLines: 2 },
      fonts: { header: "Fredoka One", body: "Nunito" },
      scroll: { pixelsPerSecond: 70, gapBetweenLoops: 100 },
      header: {
        height: "60px",
        background: { color: "#ff6b35", opacity: 0.9 },
        border: { color: "#ff8c5a", width: "2px", radius: "10px" },
        fontSize: "30px",
        fontColor: "#ffffff",
        padding: "10px",
      },
      body: {
        background: { color: "#1a0a2e", opacity: 0.8 },
        border: { color: "#9b59b6", width: "1px", radius: "0 0 10px 10px" },
        padding: { vertical: "5px", horizontal: "5px" },
      },
      task: {
        background: { color: "#2d1b4e", opacity: 0.85 },
        border: { color: "#9b59b6", width: "1px", radius: "8px" },
        fontSize: "25px",
        fontColor: "#f0e0d0",
        usernameColor: "#ff6b35",
        padding: "10px",
        marginBottom: "5px",
        maxWidth: "100%",
        direction: "row",
      },
      taskDone: { background: { color: "#1a0a2e", opacity: 0.5 }, fontColor: "#806080" },
      checkbox: {
        size: "20px",
        background: { color: "#1a0a2e", opacity: 0 },
        border: { color: "#ff6b35", width: "1px", radius: "3px" },
        margin: { top: "6px", left: "2px", right: "5px" },
        tickChar: "\u2714",
        tickSize: "18px",
        tickColor: "#ff6b35",
      },
      bullet: { char: "\u2022", size: "20px", color: "#ff6b35", margin: { top: "0px", left: "2px", right: "5px" } },
    },
  },

  // 10. Twitch Purple
  {
    id: "twitch-purple",
    name: "Twitch Purple",
    description: "Twitch brand colors with purple accents",
    preview: { bg: "#18181b", accent: "#9146FF", text: "#efeff1" },
    timerStyles: {
      dimensions: { width: "250px", height: "250px" },
      background: { color: "#18181b", opacity: 0.9, borderRadius: "50%" },
      text: { color: "#efeff1", outlineColor: "#18181b", outlineSize: "0px", fontFamily: "Inter" },
      fontSizes: { label: "24px", time: "48px", cycle: "20px" },
    },
    taskStyles: {
      display: { showDone: true, showCount: true, useCheckboxes: true, crossOnDone: true, numberOfLines: 2 },
      fonts: { header: "Inter", body: "Inter" },
      scroll: { pixelsPerSecond: 70, gapBetweenLoops: 100 },
      header: {
        height: "60px",
        background: { color: "#9146FF", opacity: 0.95 },
        border: { color: "#bf94ff", width: "0px", radius: "10px" },
        fontSize: "30px",
        fontColor: "#ffffff",
        padding: "10px",
      },
      body: {
        background: { color: "#18181b", opacity: 0.9 },
        border: { color: "#2f2f35", width: "1px", radius: "0 0 10px 10px" },
        padding: { vertical: "5px", horizontal: "5px" },
      },
      task: {
        background: { color: "#26262c", opacity: 0.9 },
        border: { color: "#3a3a44", width: "1px", radius: "6px" },
        fontSize: "25px",
        fontColor: "#efeff1",
        usernameColor: "#bf94ff",
        padding: "10px",
        marginBottom: "5px",
        maxWidth: "100%",
        direction: "row",
      },
      taskDone: { background: { color: "#18181b", opacity: 0.6 }, fontColor: "#636366" },
      checkbox: {
        size: "20px",
        background: { color: "#18181b", opacity: 0 },
        border: { color: "#9146FF", width: "1px", radius: "3px" },
        margin: { top: "6px", left: "2px", right: "5px" },
        tickChar: "\u2714",
        tickSize: "18px",
        tickColor: "#9146FF",
      },
      bullet: { char: "\u2022", size: "20px", color: "#9146FF", margin: { top: "0px", left: "2px", right: "5px" } },
    },
  },
];
