name: CI

on:
  push:
    branches: [dev, main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      SKIP_ENV_VALIDATION: "true"
      NEXT_PUBLIC_SERVER_URL: "http://localhost:3000"
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install --frozen-lockfile
      - run: bun run check-types
      - run: bun run build
      - run: bun run test
